**Пример №1** Векторизация и оптимизация кода

In [5]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b # Быстрое сложение массивов
print(result)

[5 7 9]


**Пример №2** Создание массива и операции с массивами

In [7]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2 # [5, 7, 9]
print(result)

[5 7 9]


**Пример №3** Матричные операции

In [8]:
import numpy as np
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2) # Матричное умножение
print(result)

[[19 22]
 [43 50]]


**Пример №4** Статистические функции

In [15]:
import numpy as np
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data) # Среднее значение
std_dev = np.std(data) # Стандартное отклонение
print(data, mean, std_dev)

[1 2 3 4 5] 3.0 1.4142135623730951


**Пример №5** Доступ к элементам массива

In [28]:
import numpy as np
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)
print("-----------------------")
print(m[1,0])
print("-----------------------")
print(m[1,:])
print("-----------------------")
print(m[:,2])
print("-----------------------")
print(m[1,2:])
print("-----------------------")
print(m[0:2,1])
print("-----------------------")
cols = [0, 1, 3]
print(m[:,cols])
print("-----------------------")

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]
-----------------------
5
-----------------------
[[5 6 7 8]]
-----------------------
[[3]
 [7]
 [5]]
-----------------------
[[7 8]]
-----------------------
[[2]
 [6]]
-----------------------
[[1 2 4]
 [5 6 8]
 [9 1 7]]
-----------------------


**Пример №6** Расчёт статистик по данным в массиве

In [37]:
import numpy as np
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)
print("-----------------------")
print(type(m))
print("-----------------------")
print(m.shape)
print("-----------------------")
print(m.max())
print("-----------------------")
print(m.max(axis=1))
print("-----------------------")
print(m.max(axis=0))
print("-----------------------")
print(m.mean())
print("-----------------------")
print(m.mean(axis=1))
print("-----------------------")
print(m.sum())
print("-----------------------")
print(m.sum(axis=0))

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]
-----------------------
<class 'numpy.matrix'>
-----------------------
(3, 4)
-----------------------
9
-----------------------
[[4]
 [8]
 [9]]
-----------------------
[[9 6 7 8]]
-----------------------
4.833333333333333
-----------------------
[[2.5]
 [6.5]
 [5.5]]
-----------------------
58
-----------------------
[[15  9 15 19]]


**Пример №7** Использование boolean массива для доступа к ndarray

In [40]:
import numpy as np
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
letters = np.array(['a', 'b', 'c', 'd', 'a', 'e', 'b'])

less_than_5 = nums < 5
print(less_than_5)

pos_a = letters == 'a'
print(pos_a)

print(nums[less_than_5])

[ True  True  True  True False False False False False False]
[ True False False False  True False False]
[1 2 3 4]


**Пример №8** Диагональная матрица

In [45]:
import numpy as np
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')
diag = np.diag(m_sqr_mx)
print(diag)

m_diag_np = np.diag(np.diag(m_sqr_mx))
print(m_diag_np)

# единичная матрица
m_eye = np.eye(3)
print(m_eye)

[1 5 9]
[[1 0 0]
 [0 5 0]
 [0 0 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Пример №9** Транспонирование матрицы

In [49]:
import numpy as np
A = np.matrix('1 2 3; 4 5 6')
print(A)

A_t = A.transpose() # print(A.T) сокращённый вариант записи
print(A_t)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
