**Задание 1. Создание и изменение массивов** Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9. Умножьте все элементы массива на 2. Замените все элементы больше 10 на 0. Выведите итоговый массив.

In [1]:
import numpy as np

array = np.arange(1, 10).reshape(3, 3)
array = array * 2
array[array > 10] = 0

print(array)

[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


**Задание 2. Работа с булевыми масками** Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и выведите все элементы, которые делятся на 5 без остатка. Замените эти элементы на -1. Выведите обновленный массив.

In [2]:
import numpy as np

array = np.random.randint(1, 101, 20)
delOnFive = array[array % 5 == 0]

print("Элементы, делящиеся на 5:", delOnFive)

array[array % 5 == 0] = -1

print("Обновленный массив:", array)

Элементы, делящиеся на 5: [ 45  60  85  55 100]
Обновленный массив: [-1 11 23 11 88 68 73 94 -1 84 84 -1 54 26 28 43 13 -1 -1 17]


**Задание 3. Объединение и разбиение массивов** Создайте два массива NumPy размером 1×5, заполненные случайными числами от 0 до 50. Объедините эти массивы в один двумерный массив (по строкам). Разделите полученный массив на два массива, каждый из которых содержит 5 элементов. Выведите все промежуточные и итоговые результаты.

In [3]:
import numpy as np

array1 = np.random.randint(0, 51, (1, 5))
array2 = np.random.randint(0, 51, (1, 5))

print("Массив 1:", array1)
print("Массив 2:", array2)

# Объединенние массивов по строкам
combinedArray = np.vstack((array1, array2))

print("Объединенный массив:", combinedArray)

# Разделенние массивов на два массива
splitArrays = np.split(combinedArray, 2)

print("Разделенный массив 1:", splitArrays[0])
print("Разделенный массив 2:", splitArrays[1])

Массив 1: [[47 26 17  3 15]]
Массив 2: [[19 21 26 16  1]]
Объединенный массив: [[47 26 17  3 15]
 [19 21 26 16  1]]
Разделенный массив 1: [[47 26 17  3 15]]
Разделенный массив 2: [[19 21 26 16  1]]


**Задание 4. Генерация и работа с линейными последовательностями** Создайте массив из 50 чисел, равномерно распределенных от -10 до 10. Вычислите сумму всех элементов массива. Вычислите сумму положительных элементов. Вычислите сумму отрицательных элементов. Выведите результаты.

In [4]:
import numpy as np

array = np.linspace(-10, 10, 50)

Sum = np.sum(array)
positiveSum = np.sum(array[array > 0])
negativeSum = np.sum(array[array < 0])

print("Сумма всех элементов:", Sum)
print("Сумма положительных элементов:", positiveSum)
print("Сумма отрицательных элементов:", negativeSum)

Сумма всех элементов: 7.105427357601002e-15
Сумма положительных элементов: 127.55102040816328
Сумма отрицательных элементов: -127.55102040816327


**Задание 5. Работа с диагональными и единичными матрицами** Создайте единичную матрицу размером 4×4. Создайте диагональную матрицу размером 4×4 с диагональными элементами [5, 10, 15, 20] (без использования циклов). Найдите сумму всех элементов каждой из этих матриц. Сравните результаты. 

In [6]:
import numpy as np

# Единичная матрица размером 4×4
singleMatrix = np.eye(4)

# Диагональная матрица с диагональными элементами [5, 10, 15, 20]
diagonalMatrix = np.diag([5, 10, 15, 20])

sumOfSingle = np.sum(singleMatrix)
sumOfDiagonal = np.sum(diagonalMatrix)

print("Единичная матрица:\n", singleMatrix)
print("Сумма элементов единичной матрицы:", sumOfSingle)

print("Диагональная матрица:\n", diagonalMatrix)
print("Сумма элементов диагональной матрицы:", sumOfDiagonal)

if sumOfSingle > sumOfDiagonal:
    print("Сумма элементов единичной матрицы больше.")
elif sumOfSingle < sumOfDiagonal:
    print("Сумма элементов диагональной матрицы больше.")
else:
    print("Суммы элементов матриц равны.")

Единичная матрица:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Сумма элементов единичной матрицы: 4.0
Диагональная матрица:
 [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
Сумма элементов диагональной матрицы: 50
Сумма элементов диагональной матрицы больше.


**Задание 6. Создание и базовые операции с матрицами** Создайте две квадратные матрицы NumPy размером 3×3, заполненные случайными целыми числами от 1 до 20. Вычислите и выведите: Их сумму, разность, поэлементное произведение

In [7]:
import numpy as np

matrix1 = np.random.randint(1, 21, (3, 3))
matrix2 = np.random.randint(1, 21, (3, 3))

print("Первая матрица:\n", matrix1)
print("Вторая матрица:\n", matrix2)

sumMatrix = matrix1 + matrix2
print("Сумма матриц:\n", sumMatrix)

differenceOfMatrix = matrix1 - matrix2
print("Разность матриц:\n", differenceOfMatrix)

# Поэлементное произведение матриц
elementwiseProductOfMatrix = matrix1 * matrix2
print("Поэлементное произведение матриц:\n", elementwiseProductOfMatrix)

Первая матрица:
 [[ 1  3 14]
 [ 1 12  4]
 [16  5 11]]
Вторая матрица:
 [[14 13 19]
 [10  8 17]
 [19  1  8]]
Сумма матриц:
 [[15 16 33]
 [11 20 21]
 [35  6 19]]
Разность матриц:
 [[-13 -10  -5]
 [ -9   4 -13]
 [ -3   4   3]]
Поэлементное произведение матриц:
 [[ 14  39 266]
 [ 10  96  68]
 [304   5  88]]


**Задание 7. Умножение матриц** Создайте две матрицы NumPy: Первую размером 2×3, заполненную случайными числами от 1 до 10. Вторую размером 3×2, заполненную случайными числами от 1 до 10. Выполните матричное умножение с использованием оператора @ или функции np.dot. Выведите результат.

In [8]:
import numpy as np

matrix1 = np.random.randint(1, 11, (2, 3))
matrix2 = np.random.randint(1, 11, (3, 2))

print("Матрица 1 (2×3):\n", matrix1)
print("Матрица 2 (3×2):\n", matrix2)

resultMatrix = np.dot(matrix1, matrix2)

# Выводим результат
print("Результат матричного умножения:\n", resultMatrix)

Матрица 1 (2×3):
 [[ 4  4 10]
 [ 1  4  3]]
Матрица 2 (3×2):
 [[8 3]
 [6 1]
 [1 3]]
Результат матричного умножения:
 [[66 46]
 [35 16]]


**Задание 8. Определитель и обратная матрица** Создайте случайную квадратную матрицу 3×3. Найдите и выведите: Определитель этой матрицы. Обратную матрицу (если она существует, иначе выведите сообщение, что матрица вырождена). Используйте функции np.linalg.det и np.linalg.inv.

In [9]:
import numpy as np

matrix = np.random.randint(1, 10, (3, 3))

print("Исходная матрица:\n", matrix)

det = np.linalg.det(matrix)
print("Определитель матрицы:", det)

# Проверка на то, существует ли обратная матрица
if det != 0:
    # Нахождение обратной матрицы
    inverseMatrix = np.linalg.inv(matrix)
    print("Обратная матрица:\n", inverseMatrix)
else:
    print("Матрица вырождена, обратной матрицы не существует.")

Исходная матрица:
 [[4 9 2]
 [8 8 7]
 [3 6 4]]
Определитель матрицы: -90.99999999999997
Обратная матрица:
 [[ 0.10989011  0.26373626 -0.51648352]
 [ 0.12087912 -0.10989011  0.13186813]
 [-0.26373626 -0.03296703  0.43956044]]


**Задание 9. Транспонирование и след матрицы** Создайте матрицу NumPy размером 4×4, содержащую случайные целые числа от 1 до 50. Выведите: Исходную матрицу. Транспонированную матрицу. След матрицы (сумму элементов на главной диагонали). Используйте функцию np.trace для нахождения следа.

In [10]:
import numpy as np

matrix = np.random.randint(1, 51, (4, 4))
print("Исходная матрица:\n", matrix)

transposedMatrix = matrix.T
print("Транспонированная матрица:\n", transposedMatrix)

traceOfMatrix = np.trace(matrix)
print("След матрицы:", traceOfMatrix)

Исходная матрица:
 [[13 38  7 25]
 [22 14  7 30]
 [36 29 33 41]
 [34 39  9 10]]
Транспонированная матрица:
 [[13 22 36 34]
 [38 14 29 39]
 [ 7  7 33  9]
 [25 30 41 10]]
След матрицы: 70


**Задание 10. Системы линейных уравнений** Решите систему линейных уравнений вида: 

\begin{cases} 
2x + 3y - z = 5 \\ 
4x - y + 2z = 6 \\ 
-3x + 5y + 4z = -2 
\end{cases}

Используйте матричное представление Ax = B, где: A — матрица коэффициентов, x — вектор неизвестных, B — вектор правой части. Решите систему с помощью функции np.linalg.solve и выведите результат.

In [11]:
import numpy as np

A = np.array([[2, 3, -1],
              [4, -1, 2],
              [-3, 5, 4]])
B = np.array([5, 6, -2])
x = np.linalg.solve(A, B)

print("Решение системы:")
print("x =", x[0])
print("y =", x[1])
print("z =", x[2])

Решение системы:
x = 1.6396396396396398
y = 0.5765765765765767
z = 0.009009009009008978


**Задание 11. Индивидуальное задание Вариант 9** Оптимальный выбор топлива. Автомобиль использует три вида топлива в разных пропорциях. Бензин даёт 30 МДж энергии на литр, дизель — 35 МДж, газ — 25 МДж. Для поездки требуется 100 МДж энергии. Водитель хочет использовать бензина в два раза больше, чем газа, а количество дизеля равно количеству газа. Сколько литров каждого топлива нужно залить?

In [12]:
# Общее уравнение: 60x + 35x + 25x = 100
# Упрощаем: 120x = 100
x = 100 / 120

# Количество каждого топлива
gas = x
petrol = 2 * x
diesel = x

# Выводим результаты
print(f"Количество газа: {gas:.3f} литра")
print(f"Количество бензина: {petrol:.3f} литра")
print(f"Количество дизеля: {diesel:.3f} литра")

Количество газа: 0.833 литра
Количество бензина: 1.667 литра
Количество дизеля: 0.833 литра
